title: Jason Heylon Blog
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://blog.jasonheylon.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: /:year/:month/:day/:title.html

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about.html
  # - title: Contact
  #   url: /contact

social:
  github: jasonheylon
  # twitter: jasonheylon
  facebook: jasonheylon
  # email: xxx@gmail.com

google_analytics: "UA-58263416-1"
